### ISSUE TITLE
Support Tree-sitter syntax highlighting

### ISSUE THREAD

**Issue by Hubro** [inkarkat/vim-OnSyntaxChange#1]
**Motivation**

This plugin doesn't appear to work when syntax highlighting is provided by Tree-sitter (see [nvim-treesitter]). At least, I can't get it to work, and when I try to use `SyntaxAttr.vim` to display syntax highlighting attributes, all I get is `group: `.

If I'm just being a big n00b and it's possible to get this plugin working with Tree-sitter already, it would be nice if the README was updated to explain how.

[nvim-treesitter]: https://github.com/nvim-treesitter/nvim-treesitter

**Request and Purpose**

Would it be possible to expand this plugin to support documents with Tree-sitter provided syntax highlighting? Tree-sitter provides **much** faster and much more accurate syntax highlighting than the classic regex based approach, so I definitely believe it's the future. It's already well supported in Neovim 0.5.0 which was released just a few days ago.

**Alternatives**

Perhaps it would make more sense to make a new plugin for this? I'm not sure how realistic it is to implement in this one.

**Comment by inkarkat** [comment]
If this were a simple tweak to make it work with Neovim and Tree-sitter, I'd gladly accept a patch into the plugin - even though my plugins only "officially" support Vim, not Neovim. I doubt that it would be so easy, though. The syntax triggering is based on the [`synIDattr()`](https://vimhelp.appspot.com/eval.txt.html#synIDattr%28%29) function. If that doesn't return anything (as _SyntaxAttr.vim_ has shown), and if there's no equivalent Neovim function for that new kind of syntax, I don't see a way to implement the functionality.

**Comment by Hubro** [comment]
I feel like this should definitely be possible with Tree-sitter. Much of the hype about Tree-sitter is the ability to query the syntax tree to add functionality to the editor, like folding, adding more intelligent text objects and, of course, syntax highlighting. I'll do a little research and get back to you.
