### ISSUE TITLE
The example in the README is inefficient?

### ISSUE THREAD

**Issue by user202729** [inkarkat/vim-OnSyntaxChange#2]
Not really a bug, but I notice when I follow the example in README and put the following in
`.vim/after/ftplugin/c.vim` then, after I open some C file,
use `:e%` to reload it a few times, then
`:auto User` shows that there are multiple identical autocommands registered.

This is probably not a good idea...? (or do we assume user will responsibly use augroup?)

(side note, it might be better to register the autocmd globally because the C syntax might be embedded inside
a different syntax, but I'm not too sure about this)

**Comment by inkarkat** [comment]
Yeah, use of `:augroup` is implied, but I've added a note.
